version: "3.9"
services:
  dev:
    build: .
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - TZ=Asis/Seoul
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    stdin_open: true